---
apiVersion: v2
name: tuppr
description: A Helm chart for tuppr - Talos Linux Upgrade Controller
type: application
version: 0.0.75 # x-release-please-version
appVersion: "0.0.75" # x-release-please-version
home: https://github.com/home-operations/tuppr
sources:
  - https://github.com/home-operations/tuppr
maintainers:
  - name: home-operations
    email: contact@home-operations.com
keywords:
  - talos
  - kubernetes
  - upgrade
  - controller
annotations:
  category: Infrastructure
